[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
dport = "BVTac93rt5N9CXKDV2jpMwp8UhVVw8Qor37SmXUQ8QQ5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/lansane/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
